### PR TITLE
Add Mirador and hOCR.

### PR DESCRIPTION
**Pull request by rosiel**
Part of https://github.com/Islandora/islandora_mirador/issues/18

This PR is the result of following the instructions on Islandora Mirador's README and configuring the starter site to use Mirador blocks for books and for pages tagged with Mirador. I left the OpenSeadragon stuff present, though disabled the "If Paged Content or Publication Issue use Openseadragon" context (in favour of one that shows Mirador). You can re-enable the OpenSeadragon Paged Content context if you like. For single pages, there is a Viewer Override dropdown that includes Mirador now (as well as OpenSeadragon) so you can choose which viewer to use for displaying pages.

Another small change I made was changing the single-page manifest from Service File to Original File since most derivatives ( including hOCR in this case) happen on the Original File.

@alxp

### CODE REVIEW

**Review by alxp — APPROVED** [review]
Tested by bulk loading a folder full of TIFFs and does what it says on the tin.

**Comment by alxp** [comment]
@rosiel  I tested this and it works great. If you can resolve the conflicts I think it's good to go in.

**Comment by rosiel** [comment]
I've resolved the conflicts but it can't be used with ISLE or Playbook yet because the term doesn't install properly (when installing from existing config. it'll install fine if you install the module on an existing site), so the site won't work out of the box.

**Comment by rosiel** [comment]
Closing this in favour of one built with the "sibling media" method from https://github.com/Islandora/islandora/pull/949

**Pull request closed without merging**
