### PR TITLE
Drush 13, second attempt

### PR DESCRIPTION
**Pull request by rosiel**
I accidentally deleted the active branch of the PR for #155 . 

This is the second try!

### CODE REVIEW

**Comment by alxp** [comment]
This may be needed to stop the failing tests on https://github.com/Islandora-Devops/islandora-starter-site/pull/163#pullrequestreview-2197367423

**Comment by aOelschlager** [comment]
I am getting this error every time I run make starter_dev with the islandora-starter-site's drush-13 branch. The main branch runs just fine. I used a freshly cloned isle-dc to test this on.

Scaffolding files for islandora/islandora-starter-site:
  - NOTICE Creating a new file at [web-root]/sites/default/settings.php. Examine the contents and ensure that it came out correctly.
  - Append to [web-root]/sites/default/settings.php from assets/patches/default_settings.txt
make starter-finalize ENVIRONMENT=starter_dev
make[1]: Entering directory '/isle-dc-test-pr/isle-dc'
docker compose exec -T drupal with-contenv bash -lc 'chown -R nginx:nginx . ; echo "Chown Complete"'
Chown Complete
make drupal-database update-settings-php
make[2]: Entering directory '/isle-dc-test-pr/isle-dc'
Waiting for up to 300 seconds to connect to Database mariadb:3306
Waiting for 3306 on mariadb to open.
Database found
Validating Database credentials
mysqld is alive
Credentials are valid

                                                                               
  Command drupal:directory was not found. Drush was unable to query the datab  
  ase. As a result, many commands are unavailable. Re-run your command with -  
  -debug to see relevant log messages.                                         
                                                                               

realpath: /sites/default: No such file or directory

                                                                               
  Command drupal:directory was not found. Drush was unable to query the datab  
  ase. As a result, many commands are unavailable. Re-run your command with -  
  -debug to see relevant log messages.                                         
                                                                               

realpath: /sites/default: No such file or directory
/etc/islandora/utilities.sh: line 352: site_directory: parameter null or not set
/etc/islandora/utilities.sh: line 417: site_directory: parameter null or not set
make[2]: *** [Makefile:538: update-settings-php] Error 127
make[2]: Leaving directory '/isle-dc-test-pr/isle-dc'
make[1]: *** [Makefile:579: starter-finalize] Error 2
make[1]: Leaving directory '/isle-dc-test-pr/isle-dc'
make: *** [Makefile:175: starter_dev] Error 2

**Comment by aOelschlager** [comment]
The drupal:directory command was not found because there wasn't a connection between Drupal and Mariadb. I installed the site through the UI and it worked that way but this broke whatever was working before. I'll keep testing to see if I can find out why that's happening.

**Comment by aOelschlager** [comment]
The problem is with isle-dc's call to update-settings-php function. If I remove that call and just use the same default_settings.txt and environment variables as the isle-site-template it works.

**Comment by aOelschlager** [comment]
Just tested this pr with make starter_dev from this [pr for isle-dc](https://github.com/Islandora-Devops/isle-dc/pull/403) and it works.

**Review by aOelschlager — APPROVED** [review]

**Pull request merged**
