### PR TITLE
Use Drupal 10.

### PR DESCRIPTION
**Pull request by rosiel**
Launch site with Drupal 10.

* Updates the drupal version to 10.1
* Adds `config_update` and `context` at non-stable versions
* updates Drush
* Removes the limiter to only install components compatible with (deprecated) PHP 7.4.

Note: Drush 12 "doesn't work with the launcher" so after an update (at least) you need to invoke it with `vendor/bin/drush` rather than just `drush`. This is annoying but I don't know how to remedy it, or if it's a starter-site problem or isle-site-template problem.

### CODE REVIEW

**Comment by rosiel** [comment]
Draft until we sort out the HEADER_X_FORWARDED_ALL is deprecated thing in the site template.

**Comment by rosiel** [comment]
Also, we need Matomo to fix this known issue where it can't install from existing configs because as of Drupal 10.1, the user module doesn't get installed first and so user roles aren't available in modules' install functions. [Explanation](https://www.drupal.org/project/userprotect/issues/3349663#comment-15104566). [Ticket in matomo](https://www.drupal.org/project/matomo/issues/3363521).

**Comment by rosiel** [comment]
> Draft until we sort out the HEADER_X_FORWARDED_ALL is deprecated thing in the site template.

I've isolated the error messages to a line in the Site Template, and created [an issue](https://github.com/Islandora-Devops/isle-site-template/issues/6) and a pull request https://github.com/Islandora-Devops/isle-site-template/pull/7.

**Comment by rosiel** [comment]
The associated PR mentioned above has been merged, so this is now good for testing/merging.

**Review by seth-shaw-asu — APPROVED** [review]
Smoke test works:
1. Empty site template, used the PR branch.
2. `docker compose --profile dev up -d`
3. Inside the docker container:
  1. `composer install`
  2. Update the `settings.php` according to the instructions
  3. Cleared cache
 
Drupal status page shows Drupal 10 and I can add new items with media. 👍

Anything else we need to do before merging?

**Pull request merged**
